### ISSUE TITLE
Error when trying to use `amiibo.Client` on Python 3.8.8

### ISSUE THREAD

**Issue by IvarWithoutBones** [XiehCanCode/amiibo.py#1]
## Expected Behavior
The example from the readme succesfully executes, and shows the desired data.

## Actual Behavior
When trying to import `amiibo.Client()`, it fails with the following error:
```
Traceback (most recent call last):
  File "./amiibo.py", line 1, in <module>
    import amiibo
  File "/home/ivv/misc/projects/amiibo.py", line 3, in <module>
    client = amiibo.Client()
AttributeError: partially initialized module 'amiibo' has no attribute 'Client' (most likely due to a circular import)
```

## Steps to Reproduce the Problem

  1. Copy paste the example code from the readme
  2. Execute this with Python 3.8.8 on 4766037530f41ad11368240e994888d196783b83 
  3. Notice the program failing

## Specifications

  - Version: 4766037530f41ad11368240e994888d196783b83
  - Platform: Linux
  - Subsystem: NixOS

**Comment by ChaoticFlex** [comment]
Rename the file with different name and try it works for me!.

**Comment by XiehCanCode** [comment]
Yes you can't have the file named same as the package file.
